name: Release

on:
  push:
    tags:
      - "*"

jobs:

  build-ergohaven:
    uses: ./.github/workflows/build-ergohaven.yml

  pre-release:
    name: Pre-Release
    needs:
      - build-ergohaven
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      pull-requests: 'read'

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: ergohaven_fw

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: rename
          version: 1.0

      - name: Rename
        run: |
          cd ergohaven_fw/ergohaven_fw
          rename 's/(rev1_|rev2_)//; s/ergohaven_/'${GITHUB_REF_NAME}'_'/ *.uf2

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            ergohaven_fw/**/*.uf2